idf_component_register(
    SRCS
        "main.c"
        "auth.c"
        "session.c"
        "reg_store.c"
        "mb_slave_rtu.c"
        "data_gen.c"
        "app_config.c"
        "jt_helper.c"
        "wifi_mgr.c"
        "web_server.c"
        "json_utils.c"
        "app_lang.c"
        "ota.c"
        "sys_params.c"
        "dashboard.c"
        "fs_storage.c"
        "net_mdns.c"
        "net_time.c"
        "sys_wdt.c"
        "event_log.c"
    INCLUDE_DIRS
        "."
    EMBED_FILES
        "www/index.html"
    REQUIRES
        esp-modbus
        driver
        json
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_timer
        esp_driver_gpio
        esp_http_server
        esp_https_server
        mdns
        app_update
        esp_https_ota
        esp_http_client
        mbedtls
)
